# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bd79837b55a716468a13c322ee9bb764"
name = "Lemon Size"
handle = "lemon-size"
application_url = "https://lemon-size.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request" ]
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/redact" ]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = [ "shop/redact" ]
uri = "/webhooks/shop/redact"

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://lemon-size.vercel.app/auth",
  "https://lemon-size.vercel.app/auth/callback",
  "https://lemon-size.vercel.app/api/auth"
]

[app_proxy]
url = "https://lemon-size.vercel.app/proxy/lemon-size"
subpath = "lemon-size"
prefix = "apps"
