// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/proxy/lemon-size/size-chart": {
    params: {};
  };
  "/proxy/lemon-size/analytics": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/keyword-rules": {
    params: {};
  };
  "/app/assignments": {
    params: {};
  };
  "/app/rule-tester": {
    params: {};
  };
  "/app/size-charts": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/proxy/lemon-size/size-chart" | "/proxy/lemon-size/analytics" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/shop/redact" | "/auth/login" | "/auth/*" | "/app" | "/app/keyword-rules" | "/app/assignments" | "/app/rule-tester" | "/app/size-charts" | "/app/additional" | "/app/analytics";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/proxy.lemon-size.size-chart.ts": {
    id: "routes/proxy.lemon-size.size-chart";
    page: "/proxy/lemon-size/size-chart";
  };
  "routes/proxy.lemon-size.analytics.ts": {
    id: "routes/proxy.lemon-size.analytics";
    page: "/proxy/lemon-size/analytics";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/keyword-rules" | "/app/assignments" | "/app/rule-tester" | "/app/size-charts" | "/app/additional" | "/app/analytics";
  };
  "routes/app.keyword-rules.tsx": {
    id: "routes/app.keyword-rules";
    page: "/app/keyword-rules";
  };
  "routes/app.assignments.tsx": {
    id: "routes/app.assignments";
    page: "/app/assignments";
  };
  "routes/app.rule-tester.tsx": {
    id: "routes/app.rule-tester";
    page: "/app/rule-tester";
  };
  "routes/app.size-charts.tsx": {
    id: "routes/app.size-charts";
    page: "/app/size-charts";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.analytics.tsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/proxy.lemon-size.size-chart": typeof import("./app/routes/proxy.lemon-size.size-chart.ts");
  "routes/proxy.lemon-size.analytics": typeof import("./app/routes/proxy.lemon-size.analytics.ts");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.keyword-rules": typeof import("./app/routes/app.keyword-rules.tsx");
  "routes/app.assignments": typeof import("./app/routes/app.assignments.tsx");
  "routes/app.rule-tester": typeof import("./app/routes/app.rule-tester.tsx");
  "routes/app.size-charts": typeof import("./app/routes/app.size-charts.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};