// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/proxy/lemon-size": {
    params: {};
  };
  "/proxy/lemon-size/size-chart": {
    params: {};
  };
  "/proxy/lemon-size/rules": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/assignments": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/proxy/lemon-size" | "/proxy/lemon-size/size-chart" | "/proxy/lemon-size/rules" | "/auth/login" | "/auth/*" | "/app" | "/app/assignments" | "/app/additional";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/proxy.lemon-size.ts": {
    id: "routes/proxy.lemon-size";
    page: "/proxy/lemon-size" | "/proxy/lemon-size/size-chart" | "/proxy/lemon-size/rules";
  };
  "routes/proxy.lemon-size.size-chart.ts": {
    id: "routes/proxy.lemon-size.size-chart";
    page: "/proxy/lemon-size/size-chart";
  };
  "routes/proxy.lemon-size.rules.ts": {
    id: "routes/proxy.lemon-size.rules";
    page: "/proxy/lemon-size/rules";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/assignments" | "/app/additional";
  };
  "routes/app.assignments.tsx": {
    id: "routes/app.assignments";
    page: "/app/assignments";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/proxy.lemon-size": typeof import("./app/routes/proxy.lemon-size.ts");
  "routes/proxy.lemon-size.size-chart": typeof import("./app/routes/proxy.lemon-size.size-chart.ts");
  "routes/proxy.lemon-size.rules": typeof import("./app/routes/proxy.lemon-size.rules.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.assignments": typeof import("./app/routes/app.assignments.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};